### ISSUE TITLE
Error: `...hare/nvim/lazy/murmur.lua/lua/murmur/utils/highlight.lua:64: invalid key: guibg`

### ISSUE THREAD

**Issue by nyngwang** [nyngwang/murmur.lua#20]
```
   Error  19:02:28 notify.error lazy.nvim Failed to run `config` for murmur.lua

...hare/nvim/lazy/murmur.lua/lua/murmur/utils/highlight.lua:64: invalid key: guibg

# stacktrace:
  - /murmur.lua/lua/murmur/utils/highlight.lua:64 _in_ **create_highlights**
  - /murmur.lua/lua/murmur/init.lua:63 _in_ **setup**
  - .config/nvim/lua/plugins/UX.lua:249 _in_ **config**
  - .config/nvim/lua/plugins/init.lua:66
  - .config/nvim/init.lua:2

```

**Comment by willothy** [comment]
Likely just a case of confused names in highlight.lua, I see you've pushed a possible fix so hope that works, but if not I'll make sure I get that done tomorrow.

**Comment by nyngwang** [comment]
> Maybe the configs should be changed to fg and bg as well since those are the real keys in `vim.api.nvim_set_hl`?

Yes. It seems that `nvim_set_hl` cannot accept `guibg` and `guifg` even if both `fg`, `bg` are provided.

**Comment by willothy** [comment]
This is correct, though that shouldn't be too hard to handle. The benefit of using `nvim_set_hl` is that we can now accept properties like `bold` and `underline`, and we create the highlights by simply passing the config table to `nvim_set_hl` instead of using string.format and calling vimscript.

**Comment by nyngwang** [comment]
I found another problem during my fixing of this: if a user doesn't define the `murmur_cursor_rgb_current`, then `nvim_set_hl` won't create it after Neovim starts.

**Comment by willothy** [comment]
> I found another problem during my fixing of this: if a user doesn't define the `murmur_cursor_rgb_current`, then `nvim_set_hl` won't create it after Neovim starts.

I thought I set it by default if it wasn't set in the config. I'll look into that though. In the mean time I've come up with a far more consistent way of fetching highlight colors. Refactor incoming today.

**Comment by willothy** [comment]
Been busy for a couple of days, will try to get this in tonight though.
