### ISSUE TITLE
Let users decide the min_len for highlighting

### ISSUE THREAD

**Issue by NewComer00** [nyngwang/murmur.lua#3]
Hello! Thanks for developing this blazing fast plugin!
I got some variables with length shorter than 3, maybe it's better to let users decide the "min_len" for highlighting?
https://github.com/nyngwang/murmur.lua/blob/eee21b860a1408d0b6a0f39b44b4f2bf02909185/lua/murmur.lua#L93

**Comment by nyngwang** [comment]
@NewComer00 Yes, this can absolutely be done. I will add it later. And thanks for your using :)

More about this magical number: I used to feel it annoying since it also highlighted identifiers like `if`, `or`, etc. I did guess that someday someone will need it. Now it's the timing...

**Comment by nyngwang** [comment]
The last commit, b7fc2b3, should fix it.
