### ISSUE TITLE
[FR] How about auto-switching the `cursor_rgb` dynamically based on the mode we're in?

### ISSUE THREAD

**Issue by nyngwang** [nyngwang/murmur.lua#4]

**Comment by pesader** [comment]
I think it would be nice to expose the highlight group `CURSOR_RBG` so users (and colorschemes) could set it up more easily. This would also allow changing its values using autocommands, so as to change its color based on the mode we're in :)

**Comment by nyngwang** [comment]
@pesader Good idea! I will do it later.

**Comment by pesader** [comment]
Nice! Thanks for developing `murmur`, I've happily replaced `illuminate` with it :)

**Comment by nyngwang** [comment]
@pesader Sorry for my late update. So many things happened *the last year*. Now this is the new syntax to customize your cursor rgb:

```lua
require('murmur').setup {
  cursor_rgb = {
    guibg = 'pink', -- or thing like #123456.
  },
```

and you can change it **anytime** by `hi murmur_cursor_rgb` once you feel boring during coding :)

**Comment by pesader** [comment]
Hey, that's awesome! Thank you and happy new year!
