### ISSUE TITLE
Word Highlighting doesn't work anymore after update

### ISSUE THREAD

**Issue by marcomayer** [nyngwang/murmur.lua#9]
Using a minimal config of:
```
	require("murmur").setup({
		max_len = 80,
		min_len = 1
        }

```
Words don't get highlighted anymore. I just switched to lazy.nvim for plugin management so I thought that's the issue but going back to commit b7fc2b3  things work fine again.

**Comment by marcomayer** [comment]
Thanks, that fixes it!

**Comment by nyngwang** [comment]
@marcomayer FYI: While unrelated, but it seems that there are some troubles(it seems that the cache mechanism is broken) with lazy.nvim at the moment you read my message. If you call a function of any plugin(e.g. `require('foo').do_some_work()`) inside some `autocmd`s(in my case `VimLeavePre` and `DirChanged`), then these plugins will act as "do-nothing".
